// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load environment variables based on NODE_ENV
const envFile = process.env.env === "prod" ? ".env.production" : ".env.development";
config({ path: `${process.cwd()}/${envFile}` });

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl) {
  throw new Error(`DATABASE_URL is not set. Please check your ${envFile} file.`);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});