// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load environment variables based on NODE_ENV
const envFile = process.env.NODE_ENV === "production" ? ".env.production" : ".env";
config({ path: `${process.cwd()}/${envFile}` });

const directUrl = process.env["DIRECT_URL"];
const databaseUrl = process.env["DATABASE_URL"];
const urlToUse = directUrl || databaseUrl;

if (!urlToUse) {
  throw new Error(`Neither DIRECT_URL nor DATABASE_URL is set. Please check your ${envFile} file.`);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: urlToUse,
  },
});